app:
  app_name: "lottery-system" # 应用名称
  version: "v1.0.1" # 版本
  port: 8081    # 服务启用端口
  run_mode: dev # 可选dev、release模式


log:
  log_pattern: file # 可选stdout, stderr, file模式
  log_path: ./log/server.log # 日志路径
  save_days: 5 # 保存天数
  level: info # panic,fatal,error,warn,info,debug,trace

db:
  host: "121.43.102.177"           # host
  port: 8088                # port
  user: "root"              # user
  password: "123456"        # password
  database: "lottery_system" # dbname
  max_idle_conn: 5          # 最大空闲连接数
  max_open_conn: 20         # 最大连接数
  max_idle_time: 300        # 最大空闲时间

log_config:
  level: info
  log_path: ./log
  file_name: bitstorm.log
  max_age: 24
  max_size: 1
  compress: true
  max_backups: 10

redis:
  rhost: "127.0.0.1"
  rport: 6379
  rdb: 0
  passwd: ''
  poolsize: 100